name: Dispatch sync event to plasma-contracts-private

on:
  push:
    branches: [master]

jobs:
  dispatch-sync-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        # if: github.repository == 'omisego/plasma-contracts'
        run: |
          curl -X POST https://api.github.com/repos/omisego/plasma-contracts-private/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'authorization: token '${{ secrets.HOUSE_KEEPER_BOT_TOKEN }}'' \
          --data '{"event_type": "sync-from-public", "client_payload": { "sha": "'"${{ github.sha }}"'" }}'
